<<<<<<< Updated upstream
# Generated by Django 3.0 on 2021-08-24 15:55
=======
# Generated by Django 3.0 on 2021-08-24 17:52
>>>>>>> Stashed changes

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación', verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificación', verbose_name='Modificado')),
                ('descripcion', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=10)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
