# Generated by Django 3.0 on 2021-08-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='nivel',
        ),
    ]
