# Generated by Django 3.0 on 2021-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='mostrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
