# Generated by Django 3.0 on 2021-08-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='tipo',
            new_name='correcta',
        ),
    ]
