# Generated by Django 3.0 on 2021-08-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='dificultad',
            field=models.IntegerField(default=1),
        ),
    ]
